DEBUG = True
DISABLE_AUTH = True
NO_BACKGROUND = True
TARGET_CURRENCY = 'USD'
DEPTH = 10
API_TRADE_URL = 'http://testapi/v2/candles/trade'
RATES_UPDATES_DELAY = 999999

SQLALCHEMY_DATABASE_URI = 'sqlite:////:memory'
