DEBUG = True
DISABLE_AUTH = True
GRABBER_IN_APP_THREAD = True
TARGET_CURRENCY = 'USD'
DEPTH = 10
API_TRADE_URL = 'http://trade-api.dev/v2/candles/trade'
RATES_UPDATES_DELAY = 999999

SQLALCHEMY_DATABASE_URI = 'sqlite:////:memory'
