version: "2"
services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trades
  api:
    build: .
    links:
      - db
    ports:
      - "5002:5002"  
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=${TZ}