version: "2"
services:
  api:
    build: .
    links:
      - db
    ports:
      - "5002:5002"  
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro